[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Directory with serverless functions, including background
  # functions, to deploy. This is an absolute path relative to the 
  # base directory, which is the root by default (/).
  directory = "netlify/functions/"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"

[headers]
  [[headers]]
    for = "*"
    [headers.values]
      Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self';"
